# Generated by Django 2.0.1 on 2018-01-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
